version: "3.8"
services:
  Api_Service:
    restart: always
    build: 
      context: ./Api_Service
    ports:
      - 8080:3000
    networks:
      - public

  subscriptions:
    restart: always
    build: 
      context: ./subscription
    ports:
      - 8081:3000
    networks:
      - public
      - private

  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - private
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb:/data/db

  rabbitmq:
    image: rabbitmq:3
    restart: always
    volumes:
      - "./rabbitmq/db:/var/lib/rabbitmq"
    networks:
      - private
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  mailing:
    restart: always
    build: 
      context: ./mailing
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - private

networks:
  public:
  private:
    internal: true